#!/usr/bin/env zsh

function findColorDefinition() {
    findColorDefinitionRec $1 $2 0
}

function findColorDefinitionRec() {
   local result=$(cat "$1" | grep -e "$2" | sed -e 's/^.* //')
if [[ "$result" =~ "#......" ]]; then
    echo $result
elif [ $3 -eq 0 ]; then
    findColorDefinitionRec $1 "^#define $result" 1
else
    echo "Could not find color definition"
fi
}

local cursorColor
local colorDirectory="$HOME/.color"
local awesomeThemeDirectory="$HOME/.config/awesome/themes"
local ext='.gen'
local xResourcesInclude="current$ext"
local dirColorsSymlink="$HOME/.dir_colors"
local vimInclude="$HOME/.vim/current$ext"
local currentDirectory=$(pwd)
cd $colorDirectory

if [ $1 = 'solarized_light' ]; then
    cat solarized/solarized | sed -e 's/^\(#define S_base\)/!! \1/' -e 's/^! \(#define S_base\)/\1/' > $xResourcesInclude
    echo -e "colorscheme solarized\nset background=dark" > $vimInclude
    ln -fs $colorDirectory/dircolors-solarized/dircolors.ansi-light $dirColorsSymlink
    cursorColor=9 
elif [ $1 = 'tomorrow_dark' ]; then
    cat base16-xresources/base16-tomorrow.dark.xresources > $xResourcesInclude
    echo -e "colorscheme base16-tomorrow\nset background=dark" > $vimInclude
    ln -fs $colorDirectory/dircolors-solarized/dircolors.ansi-dark $dirColorsSymlink
    cursorColor=3
elif [ $1 = 'eighties_dark' ]; then
    cat base16-xresources/base16-eighties.dark.xresources > $xResourcesInclude
    echo -e "colorscheme base16-eighties\nset background=dark" > $vimInclude
    ln -fs $colorDirectory/dircolors-solarized/dircolors.ansi-dark $dirColorsSymlink
    cursorColor=3
elif [ $1 = 'custom1' ]; then
    cat xcolors/themes/tango > $xResourcesInclude
    echo -e "colorscheme lucius\nLuciusDark" > $vimInclude
    rm -rf $dirColorsSymlink
    cursorColor=11
else
    echo "$(basename $0): not supported"
    return 1
fi

echo -e "\nURxvt.cursorColor: $cursorColor" >> $xResourcesInclude
local borderNormal=$(findColorDefinition $xResourcesInclude ".*background:")
echo $borderNormal > $awesomeThemeDirectory/borderNormal$ext
local borderFocus=$(findColorDefinition $xResourcesInclude ".*color$cursorColor:")
echo $borderFocus > $awesomeThemeDirectory/borderFocus$ext
xrdb ~/.Xresources
killall -s HUP awesome
cd $currentDirectory
return 0

